# Generated by Django 5.0.7 on 2024-08-06 06:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Images'),
        ),
    ]
